<a href="https://colab.research.google.com/github/jocelynbrownie27-max/Cholesterol-Project/blob/main/DSRP_2026_Jocelyn_Browne_(CHOLESTEROL).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv('/content/NCD_RisC_Nature_2020_Cholesterol_age_standardised_countries.csv')
df

,Country/Region/World,ISO,Sex,Year,Mean total cholesterol (mmol/L),Mean total cholesterol lower 95% uncertainty interval (mmol/L),Mean total cholesterol upper 95% uncertainty interval (mmol/L),Mean non-HDL cholesterol (mmol/L),Mean non-HDL cholesterol lower 95% uncertainty interval (mmol/L),Mean non-HDL cholesterol upper 95% uncertainty interval (mmol/L),Mean HDL cholesterol (mmol/L),Mean HDL cholesterol lower 95% uncertainty interval (mmol/L),Mean HDL cholesterol upper 95% uncertainty interval (mmol/L)
0,Afghanistan,AFG,Men,1980,4.263545,3.539636,4.959936,2.919134,2.486837,3.339214,1.221839,0.926460,1.497237
1,Afghanistan,AFG,Men,1981,4.266327,3.569655,4.931141,2.934723,2.512884,3.344176,1.214738,0.932500,1.476955
2,Afghanistan,AFG,Men,1982,4.269252,3.612601,4.904159,2.950451,2.543536,3.345615,1.207716,0.935305,1.462378
3,Afghanistan,AFG,Men,1983,4.272437,3.646602,4.881011,2.966397,2.570361,3.353339,1.200752,0.943039,1.444552
4,Afghanistan,AFG,Men,1984,4.275822,3.673783,4.866126,2.982507,2.598309,3.360546,1.193839,0.947619,1.427836
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15595,Zimbabwe,ZWE,Women,2014,4.161298,3.755729,4.588048,2.945255,2.711719,3.174748,1.312036,1.140103,1.483028
15596,Zimbabwe,ZWE,Women,2015,4.157357,3.710967,4.625261,2.945829,2.704246,3.184318,1.310691,1.126460,1.491962
15597,Zimbabwe,ZWE,Women,2016,4.153718,3.661819,4.663383,2.946790,2.694693,3.195830,1.309282,1.110321,1.504699
15598,Zimbabwe,ZWE,Women,2017,4.150368,3.608575,4.709977,2.948084,2.683316,3.207449,1.307992,1.093114,1.517367
15599,Zimbabwe,ZWE,Women,2018,4.147003,3.544370,4.768410,2.949272,2.669244,3.222524,1.306701,1.077158,1.532687

#Cleaning Data

In [3]:
df.isna().sum()

Country/Region/World                                                0
ISO                                                                 0
Sex                                                                 0
Year                                                                0
Mean total cholesterol (mmol/L)                                     0
Mean total cholesterol lower 95% uncertainty interval (mmol/L)      0
Mean total cholesterol upper 95% uncertainty interval (mmol/L)      0
Mean non-HDL cholesterol (mmol/L)                                   0
Mean non-HDL cholesterol lower 95% uncertainty interval (mmol/L)    0
Mean non-HDL cholesterol upper 95% uncertainty interval (mmol/L)    0
Mean HDL cholesterol (mmol/L)                                       0
Mean HDL cholesterol lower 95% uncertainty interval (mmol/L)        0
Mean HDL cholesterol upper 95% uncertainty interval (mmol/L)        0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

No duplicated or null values

In [17]:
df.value_counts(['Country/Region/World'])

Country/Region/World
Afghanistan             78
Albania                 78
Algeria                 78
American Samoa          78
Andorra                 78
                        ..
Venezuela               78
Viet Nam                78
Yemen                   78
Zambia                  78
Zimbabwe                78
Name: count, Length: 200, dtype: int64

78 total observations for each country, 39 men, 39 women

In [22]:
df = df.drop(columns=['ISO'])
df

KeyError: "['ISO'] not found in axis"